networks:
  analytics-net:
    external: {name: shared-analytics-network}
  dmz-net:
    external: {name: shared-dmz-network}
services:
  password-api:
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [node.platform.os == windows]
      replicas: 4
    image: sixeyed/password-api:v3
    networks: {analytics-net: null, dmz-net: null}
  password-web:
    deploy:
      placement:
        constraints: [node.platform.os == linux, node.role == worker]
      replicas: 6
    environment: {'PasswordApi:Url': 'http://api.sixeyed.com'}
    image: something
    networks: {dmz-net: null}
version: '3.3'
